services:
  AILogue-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - AILogue-backend
  AILogue-backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - AILogue-db
    env_file:
      - ./backend/.env
    networks:
      - AILogue-network
  AILogue-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=AILogue
      - POSTGRES_DB=AILogue-db
      - POSTGRES_PASSWORD=AILogue-password
    ports:
      - "5432:5432"
    networks:
      - AILogue-network

networks:
  AILogue-network:
    driver: bridge

# To connect to the db, use the following connection string:
# postgres://AILogue:AILogue-password@localhost:5432/AILogue-db

volumes:
  db-data:
