services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aireader
      POSTGRES_PASSWORD: aireader-password
      POSTGRES_DB: aireader-db
    ports:
      - "5432:5432"

# To connect to the db, use the following connection string:
# postgres://aireader:aireader-password@localhost:5432/aireader-db
